name: Github Explorer CI/CD Pipeline - Render

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn test
      - name: Set up GitHub API token
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: echo "GH_API_TOKEN=${GH_API_TOKEN}" >> $GH_API_TOKEN
      - name: Run integration tests
        run: mvn clean verify

  deploy:
    name: Deploy to Render
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          find . -name Dockerfile
          docker build -t my-image .
#      - name: Push Docker image
#        uses: docker/login-action@v2
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#      - name: Push Docker image
#        run: docker push my-image
#      - name: Deploy to Render
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: ${{ secrets.RENDER_SERVICE_ID }}
#          api-key: ${{ secrets.RENDER_API_KEY }}

#  - name: Publish to Docker Hub
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_TOKEN }}
#        repository: dockerHubUser/dockerHubRepository
#        tags: ${{github.run_number}}


