name: Github Explorer CI/CD Pipeline - Render

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn test -e -X
      - name: Set up GitHub API token
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: echo "GH_API_TOKEN=${GH_API_TOKEN}" >> $GH_API_TOKEN
      - name: Run integration tests
        run: mvn clean verify

  deploy:
    name: Deploy to Render
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      -
      - name: Build Docker image
        run: docker build -t my-image .