name: Github Explorer CI/CD Pipeline - Render

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn test
      - name: Set up GitHub API token
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: echo "GH_API_TOKEN=${GH_API_TOKEN}" >> $GH_API_TOKEN
      - name: Run integration tests
        run: mvn clean verify
  deploy:
    name: Deploy to Render
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Build Docker image
        run:
          docker build -t githurepoexplorer .
      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: | 
          docker tag githurepoexplorer ${{ secrets.DOCKER_USERNAME }}/githurepoexplorer:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/githurepoexplorer:latest
      - name: Trigger Render Deploy Hook
        run: |
            curl -X POST https://api.render.com/deploy/srv-cjkuuegcfp5c73dif120?key=4_Ho9CfQXBM \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

